### ISSUE TITLE
Server isn't working with the newest app version

### ISSUE THREAD

**Issue by bobness** [bobness/inspect-app#32]
I published 1.0.0. v5 to App Store Connect and then Test Flight, and it results in the same behavior I was seeing in the simulator last week. 

When you login, the `HomeScreen` spinner is there forever.

And from the server's pm2/npm log:

```
0|npm      | (node:13273) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
0|npm      | (node:13273) UnhandledPromiseRejectionWarning: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
0|npm      |     at /home/ec2-user/inspect-service/middleware/functions.js:52:64
0|npm      |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
0|npm      |     at async Promise.all (index 4)
0|npm      |     at async getSummaries (/home/ec2-user/inspect-service/middleware/functions.js:50:5)
0|npm      |     at async /home/ec2-user/inspect-service/routes/unread_summaries.js:16:21
0|npm      | (node:13273) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
0|npm      | (node:13273) UnhandledPromiseRejectionWarning: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
0|npm      |     at /home/ec2-user/inspect-service/middleware/functions.js:52:64
0|npm      |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
0|npm      |     at async Promise.all (index 4)
0|npm      |     at async getSummaries (/home/ec2-user/inspect-service/middleware/functions.js:50:5)
0|npm      |     at async /home/ec2-user/inspect-service/routes/unread_summaries.js:16:21
0|npm      | (node:13273) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

**Comment by bobness** [comment]
Also, I can't reproduce this on my local machine for some reason...
