### ISSUE TITLE
Fix why the `inspect-service` occasionally breaks

### ISSUE THREAD

**Issue by bobness** [bobness/inspect-app#42]

**Comment by bobness** [comment]
As I suspected, it was `pg` pool timing out in connecting:

```
(node:2181) UnhandledPromiseRejectionWarning: Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/home/ec2-user/inspect-service/node_modules/pg-pool/index.js:200:27)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2181) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2181) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2181) UnhandledPromiseRejectionWarning: Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/home/ec2-user/inspect-service/node_modules/pg-pool/index.js:200:27)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:2181) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by bobness** [comment]
Added `process.exit()` in a `try/catch` block for when pg pool fails to connect. Since pm2 will restart the service, hopefully this fixes it 🤞
